---
section: Backend
group: Security
path: backend/security
levels:
- level: 0
  description: ''
  goals: []
  skills: []
- level: 1
  description: Cleans requests from API
  goals: []
  skills: []
- level: 2
  description: Defends against CSRF and XSS, can set up SSL certs
  goals: []
  skills: []
- level: 3
  description: Defends against brute-force/DDoS attacks
  goals: []
  skills: []
