title: Web Development JS
email: info@learnersguild.org
description: >
  This repository stores information useful for learning the craft
  of web development.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
source: client
destination: public
collections:
  api:
    output: true
