title: Web Development JS
email: info@learnersguild.org
description: >
  This repository stores information useful for learning the craft
  of web development.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
destination: public
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - bin
  - library
  - playlists
  - guides
collections:
  api:
    output: true
